# Jupyter Book configuration
# Más opciones: https://jupyterbook.org/en/stable/customize/config.html
title: "Ames Housing: Regresión lineal, inferencia, diagnóstico y métodos robustos"
author: "Tu nombre / equipo"
language: es
only_build_toc_files: true

repository:
  url: https://github.com/usuario/ames-housing-project  # Cambia esto
  path_to_book: ./
  branch: main

html:
  favicon: ""
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true

parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence
    - linkify
    - substitution
    - tasklist

sphinx:
  config:
    numfig: true
    mathjax_config:
      TeX:
        equationNumbers:
          autoNumber: "all"
