# Jupyter Book configuration
# Más opciones: https://jupyterbook.org/en/stable/customize/config.html
title: "Ames Housing: Regresión lineal, inferencia, diagnóstico y métodos robustos"
author: "Gloria Bastidas - Daniel Carbono - Luis Perez"
language: es
only_build_toc_files: true

repository:
  url: https://github.com/Globast/ames-housing-project  # Cambia esto
  path_to_book: ./
  branch: main

html:
  favicon: ""
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false
  home_page_in_navbar: false

parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence
    - linkify
    - substitution
    - tasklist

sphinx:
  config:
    numfig: true                  
    numfig_secnum_depth: 2  
    math_numfig: true      
    mathjax3_config:
      tex:
        tags: 'all'               
        inlineMath: [['$', '$'], ['\\(', '\\)']]

